package com.mycompany.elgamal_java_project.View;

import com.mycompany.elgamal_java_project.controller.ElGamalController;
import javax.swing.JOptionPane;


public class ElgamalView extends javax.swing.JFrame {

    /**
     * Creates new form ElgamalView
     */
    
    private ElGamalController controller;
    public ElgamalView() {
        initComponents();
    }
    
    public void SetController(ElGamalController _controller){
        controller = _controller;
    }
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(null, message); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneratorPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pInputKey = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        aInputKey = new javax.swing.JTextField();
        genarateKeyButton = new javax.swing.JButton();
        genarateKeyRandomButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        privateKeyLabel = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        publicKeyLabel = new javax.swing.JTextArea();
        moveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        EncryptPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pInputEncypt = new javax.swing.JTextField();
        aInputEncrypt = new javax.swing.JTextField();
        yInputEncypt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        paintextInput = new javax.swing.JTextArea();
        uploadFileEncryptButton = new javax.swing.JButton();
        encryptButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        c1CipherText = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        c2CipherText = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        saveEncryptButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        c2CipherTextDecrypt = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        c1CipherTextDecrypt = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        uploadFileDecryptButton = new javax.swing.JButton();
        decryptButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        resultDecrypt = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        saveDecryptButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        privateKeyDecrypt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        GeneratorPanel.setBackground(new java.awt.Color(210, 210, 210));
        GeneratorPanel.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tạo Khóa");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Số nguyên tố p:");

        pInputKey.setBackground(new java.awt.Color(204, 204, 204));
        pInputKey.setForeground(new java.awt.Color(0, 0, 0));
        pInputKey.setToolTipText("");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Số a (Phần tử nguyên thủy của p)");

        aInputKey.setBackground(new java.awt.Color(204, 204, 204));
        aInputKey.setForeground(new java.awt.Color(0, 0, 0));
        aInputKey.setToolTipText("");

        genarateKeyButton.setBackground(new java.awt.Color(153, 153, 153));
        genarateKeyButton.setForeground(new java.awt.Color(0, 0, 0));
        genarateKeyButton.setText("Tạo khóa");
        genarateKeyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genarateKeyButtonMouseClicked(evt);
            }
        });

        genarateKeyRandomButton.setBackground(new java.awt.Color(153, 153, 153));
        genarateKeyRandomButton.setForeground(new java.awt.Color(0, 0, 0));
        genarateKeyRandomButton.setText("Tạo khóa ngẫu nhiên");
        genarateKeyRandomButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genarateKeyRandomButtonMouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Khóa bí mật (X):");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        privateKeyLabel.setEditable(false);
        privateKeyLabel.setBackground(new java.awt.Color(204, 204, 204));
        privateKeyLabel.setColumns(20);
        privateKeyLabel.setForeground(new java.awt.Color(51, 51, 51));
        privateKeyLabel.setLineWrap(true);
        privateKeyLabel.setRows(5);
        jScrollPane2.setViewportView(privateKeyLabel);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Khóa công khai (Y):");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        publicKeyLabel.setEditable(false);
        publicKeyLabel.setBackground(new java.awt.Color(204, 204, 204));
        publicKeyLabel.setColumns(20);
        publicKeyLabel.setForeground(new java.awt.Color(51, 51, 51));
        publicKeyLabel.setLineWrap(true);
        publicKeyLabel.setRows(5);
        jScrollPane1.setViewportView(publicKeyLabel);

        moveButton.setBackground(new java.awt.Color(153, 153, 153));
        moveButton.setForeground(new java.awt.Color(0, 0, 0));
        moveButton.setText("Chuyển");
        moveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveButtonMouseClicked(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(153, 153, 153));
        resetButton.setForeground(new java.awt.Color(0, 0, 0));
        resetButton.setText("Làm mới");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout GeneratorPanelLayout = new javax.swing.GroupLayout(GeneratorPanel);
        GeneratorPanel.setLayout(GeneratorPanelLayout);
        GeneratorPanelLayout.setHorizontalGroup(
            GeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneratorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pInputKey)
                    .addComponent(aInputKey)
                    .addGroup(GeneratorPanelLayout.createSequentialGroup()
                        .addComponent(genarateKeyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(genarateKeyRandomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(GeneratorPanelLayout.createSequentialGroup()
                        .addGroup(GeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneratorPanelLayout.createSequentialGroup()
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        GeneratorPanelLayout.setVerticalGroup(
            GeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneratorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInputKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aInputKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genarateKeyButton)
                    .addComponent(genarateKeyRandomButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GeneratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveButton)
                    .addComponent(resetButton))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        EncryptPanel.setBackground(new java.awt.Color(210, 210, 210));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mã Hóa");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Khóa công khai:");

        pInputEncypt.setBackground(new java.awt.Color(204, 204, 204));
        pInputEncypt.setForeground(new java.awt.Color(0, 0, 0));

        aInputEncrypt.setBackground(new java.awt.Color(204, 204, 204));
        aInputEncrypt.setForeground(new java.awt.Color(0, 0, 0));

        yInputEncypt.setBackground(new java.awt.Color(204, 204, 204));
        yInputEncypt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("p:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("a:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Y:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Văn bản cần mã hóa:");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        paintextInput.setBackground(new java.awt.Color(204, 204, 204));
        paintextInput.setColumns(20);
        paintextInput.setForeground(new java.awt.Color(0, 0, 0));
        paintextInput.setLineWrap(true);
        paintextInput.setRows(5);
        jScrollPane3.setViewportView(paintextInput);

        uploadFileEncryptButton.setBackground(new java.awt.Color(153, 153, 153));
        uploadFileEncryptButton.setForeground(new java.awt.Color(0, 0, 0));
        uploadFileEncryptButton.setText("Chọn file");
        uploadFileEncryptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadFileEncryptButtonMouseClicked(evt);
            }
        });

        encryptButton.setBackground(new java.awt.Color(153, 153, 153));
        encryptButton.setForeground(new java.awt.Color(0, 0, 0));
        encryptButton.setText("Mã hóa");
        encryptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encryptButtonMouseClicked(evt);
            }
        });
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Kết quả:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("C1");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        c1CipherText.setEditable(false);
        c1CipherText.setBackground(new java.awt.Color(204, 204, 204));
        c1CipherText.setColumns(20);
        c1CipherText.setForeground(new java.awt.Color(51, 51, 51));
        c1CipherText.setLineWrap(true);
        c1CipherText.setRows(5);
        jScrollPane4.setViewportView(c1CipherText);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        c2CipherText.setEditable(false);
        c2CipherText.setBackground(new java.awt.Color(204, 204, 204));
        c2CipherText.setColumns(20);
        c2CipherText.setForeground(new java.awt.Color(51, 51, 51));
        c2CipherText.setLineWrap(true);
        c2CipherText.setRows(5);
        jScrollPane5.setViewportView(c2CipherText);

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("C1");

        saveEncryptButton.setBackground(new java.awt.Color(153, 153, 153));
        saveEncryptButton.setForeground(new java.awt.Color(0, 0, 0));
        saveEncryptButton.setText("Lưu");
        saveEncryptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveEncryptButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EncryptPanelLayout = new javax.swing.GroupLayout(EncryptPanel);
        EncryptPanel.setLayout(EncryptPanelLayout);
        EncryptPanelLayout.setHorizontalGroup(
            EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncryptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EncryptPanelLayout.createSequentialGroup()
                        .addGroup(EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yInputEncypt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aInputEncrypt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pInputEncypt)))
                    .addGroup(EncryptPanelLayout.createSequentialGroup()
                        .addComponent(uploadFileEncryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(encryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addComponent(saveEncryptButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EncryptPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(EncryptPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5))
                    .addGroup(EncryptPanelLayout.createSequentialGroup()
                        .addGroup(EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        EncryptPanelLayout.setVerticalGroup(
            EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncryptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pInputEncypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aInputEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yInputEncypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadFileEncryptButton)
                    .addComponent(encryptButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EncryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncryptPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EncryptPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel14)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveEncryptButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(210, 210, 210));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Giải mã");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Khóa bí mật (X)");

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        c2CipherTextDecrypt.setBackground(new java.awt.Color(204, 204, 204));
        c2CipherTextDecrypt.setColumns(20);
        c2CipherTextDecrypt.setForeground(new java.awt.Color(0, 0, 0));
        c2CipherTextDecrypt.setLineWrap(true);
        c2CipherTextDecrypt.setRows(5);
        jScrollPane7.setViewportView(c2CipherTextDecrypt);

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("C1");

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        c1CipherTextDecrypt.setBackground(new java.awt.Color(204, 204, 204));
        c1CipherTextDecrypt.setColumns(20);
        c1CipherTextDecrypt.setForeground(new java.awt.Color(0, 0, 0));
        c1CipherTextDecrypt.setLineWrap(true);
        c1CipherTextDecrypt.setRows(5);
        jScrollPane6.setViewportView(c1CipherTextDecrypt);

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("C1");

        uploadFileDecryptButton.setBackground(new java.awt.Color(153, 153, 153));
        uploadFileDecryptButton.setForeground(new java.awt.Color(0, 0, 0));
        uploadFileDecryptButton.setText("Chọn file");
        uploadFileDecryptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadFileDecryptButtonMouseClicked(evt);
            }
        });

        decryptButton.setBackground(new java.awt.Color(153, 153, 153));
        decryptButton.setForeground(new java.awt.Color(0, 0, 0));
        decryptButton.setText("Giải mã");
        decryptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decryptButtonMouseClicked(evt);
            }
        });
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        resultDecrypt.setBackground(new java.awt.Color(204, 204, 204));
        resultDecrypt.setColumns(20);
        resultDecrypt.setForeground(new java.awt.Color(51, 51, 51));
        resultDecrypt.setLineWrap(true);
        resultDecrypt.setRows(5);
        jScrollPane8.setViewportView(resultDecrypt);

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Kết quả");

        saveDecryptButton.setBackground(new java.awt.Color(153, 153, 153));
        saveDecryptButton.setForeground(new java.awt.Color(0, 0, 0));
        saveDecryptButton.setText("Lưu");
        saveDecryptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveDecryptButtonMouseClicked(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Văn bản cần giải mã (Bản mã)");

        privateKeyDecrypt.setBackground(new java.awt.Color(204, 204, 204));
        privateKeyDecrypt.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(uploadFileDecryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addComponent(saveDecryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(privateKeyDecrypt))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(privateKeyDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel18)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadFileDecryptButton)
                    .addComponent(decryptButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveDecryptButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneratorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EncryptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EncryptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GeneratorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decryptButtonActionPerformed

    private void saveDecryptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveDecryptButtonMouseClicked
        controller.SaveDecryptButtonListener();
    }//GEN-LAST:event_saveDecryptButtonMouseClicked

    private void genarateKeyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genarateKeyButtonMouseClicked
        controller.CreateAction();
    }//GEN-LAST:event_genarateKeyButtonMouseClicked

    private void genarateKeyRandomButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genarateKeyRandomButtonMouseClicked
        controller.RandomKeyAction();
    }//GEN-LAST:event_genarateKeyRandomButtonMouseClicked

    private void moveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveButtonMouseClicked
        controller.MoveKeyToEncryptAndDecrypt();
    }//GEN-LAST:event_moveButtonMouseClicked

    private void uploadFileEncryptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadFileEncryptButtonMouseClicked
        controller.UploadEncryptButtonListener();
    }//GEN-LAST:event_uploadFileEncryptButtonMouseClicked

    private void encryptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encryptButtonMouseClicked
        controller.EncryptAction();
    }//GEN-LAST:event_encryptButtonMouseClicked

    private void saveEncryptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveEncryptButtonMouseClicked
        controller.SaveEncryptButtonListener();
    }//GEN-LAST:event_saveEncryptButtonMouseClicked

    private void uploadFileDecryptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadFileDecryptButtonMouseClicked
        controller.UploadDecryptButtonListener();
    }//GEN-LAST:event_uploadFileDecryptButtonMouseClicked

    private void decryptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decryptButtonMouseClicked
        controller.DecryptAction();
    }//GEN-LAST:event_decryptButtonMouseClicked

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked
        controller.resetButtonClick();
    }//GEN-LAST:event_resetButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElgamalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElgamalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElgamalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElgamalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElgamalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EncryptPanel;
    private javax.swing.JPanel GeneratorPanel;
    public javax.swing.JTextField aInputEncrypt;
    public javax.swing.JTextField aInputKey;
    public javax.swing.JTextArea c1CipherText;
    public javax.swing.JTextArea c1CipherTextDecrypt;
    public javax.swing.JTextArea c2CipherText;
    public javax.swing.JTextArea c2CipherTextDecrypt;
    public javax.swing.JButton decryptButton;
    public javax.swing.JButton encryptButton;
    public javax.swing.JButton genarateKeyButton;
    public javax.swing.JButton genarateKeyRandomButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JButton moveButton;
    public javax.swing.JTextField pInputEncypt;
    public javax.swing.JTextField pInputKey;
    public javax.swing.JTextArea paintextInput;
    public javax.swing.JTextField privateKeyDecrypt;
    public javax.swing.JTextArea privateKeyLabel;
    public javax.swing.JTextArea publicKeyLabel;
    public javax.swing.JButton resetButton;
    public javax.swing.JTextArea resultDecrypt;
    public javax.swing.JButton saveDecryptButton;
    public javax.swing.JButton saveEncryptButton;
    public javax.swing.JButton uploadFileDecryptButton;
    public javax.swing.JButton uploadFileEncryptButton;
    public javax.swing.JTextField yInputEncypt;
    // End of variables declaration//GEN-END:variables
}
